"""Plain-English explanations shown in the app's hover (ⓘ) tooltips."""

TERMS = {
    # ---- Forecasts ---------------------------------------------------------
    "horizon": "How far ahead to forecast. Short horizons are closer to a coin flip; the range of outcomes widens the further out you go.",
    "backtest_depth": "How many past dates each model is tested on before it's trusted. More dates give fairer model weights but take longer.",
    "expected": "The average of all simulated outcomes. Half of the paths end above the median, not this number, because big up-moves pull the average up.",
    "prob_up": "The share of simulated price paths that finish above today's price. 50% means no edge either way.",
    "range80": "8 out of 10 simulated outcomes land inside this range. It's the realistic band, not a target.",
    "garch": "Current annualised volatility from a GARCH model, which captures that calm and wild periods cluster. The small number is where volatility tends to drift back to over time.",
    "fan_chart": "The shaded cone shows where the price could plausibly be. Darker bands are more likely (50%), lighter bands cover rarer outcomes (80% and 90%). The orange line is the average path.",
    "horizon_table": "The same forecast read off at checkpoints along the way.",
    "p10": "Only 10% of simulated outcomes end below this price: a bad-but-plausible case.",
    "p90": "Only 10% of simulated outcomes end above this price: a good-but-plausible case.",
    "median": "The middle outcome: half the simulated paths end above, half below.",
    "leaderboard": "Each model was re-run on past dates as if it were live, and scored on how close it got. Models that beat a simple 'price stays the same' guess get more weight in the blend.",
    "weight": "How much this model counts in the final blend, based on its past accuracy.",
    "rmse": "Root mean squared error: the typical size of the model's past misses. Lower is better.",
    "skill": "How much better than a 'no change' guess the model was. Positive means it added something; zero or negative means you're better off ignoring it.",
    "hit_rate": "How often the model called the direction (up or down) right in the backtest. 50% is a coin flip.",
    "coverage": "How often the real price actually landed inside the 80% band in testing. Close to 80% means the ranges are honest.",
    "tech_signal": "A combined read of trend and momentum indicators from −1 (bearish) to +1 (bullish). It leans on trend indicators when the stock is trending and on overbought/oversold indicators when it's range-bound.",
    "adx_regime": "ADX measures trend strength, not direction. Above 25 the stock is trending; below it's chopping sideways.",
    "hurst": "Whether moves tend to continue (above 0.55, trending), reverse (below 0.45, mean-reverting), or neither (around 0.5, random).",
    "natr": "The average daily range (ATR) as a percent of price: how much the stock typically moves in a day. Handy for sizing stops.",
    "signal_evidence": "Each bar is one indicator's vote. Green pushes the signal bullish, red pushes it bearish; longer bars count more.",
    "RSI (14)": "Relative Strength Index: momentum from 0 to 100. Above 70 is stretched to the upside, below 30 stretched to the downside. In uptrends it tends to hold 40-50 on dips.",
    "Stoch %K": "Where today's close sits within the last 14 days' range (0 = at the low, 100 = at the high).",
    "MFI (14)": "Money Flow Index: RSI that also weighs volume. Above 80 is heavy buying, below 20 heavy selling.",
    "ADX": "Trend strength from 0 to 100. Above 25 means a real trend; it says nothing about direction.",
    "+DI / -DI": "Directional indicators: +DI above −DI means up-moves are dominating, and vice versa.",
    "MACD hist": "The gap between MACD and its signal line. Positive and growing means upward momentum is building.",
    "Bollinger %B": "Where price sits in its Bollinger Bands: 1 = at the upper band, 0 = at the lower band, 0.5 = at the middle.",
    "BB width": "How wide the Bollinger Bands are relative to price. Very narrow bands often come before a big move.",
    "ATR (14)": "Average True Range: the typical daily price swing in dollars over the last 14 days.",
    "Realised vol (21d)": "How much the stock actually moved over the last month, annualised.",
    "Parkinson vol (21d)": "Volatility measured from daily highs and lows instead of closes. It picks up intraday swings that closing prices hide.",
    "vs SMA 50": "How far price is above (+) or below (−) its 50-day average.",
    "vs SMA 200": "How far price is above (+) or below (−) its 200-day average, the classic long-term trend line.",
    "vs VWAP 20": "How far price is from the volume-weighted average price of the last 20 days, roughly the average cost of recent buyers.",
    # ---- Strategy Lab ------------------------------------------------------
    "history": "How many years of data to test on. Longer tests include more market conditions (crashes, rallies, sideways years).",
    "cost": "Trading cost per buy or sell, in basis points (1 bp = 0.01%). It covers commission and slippage; 5 bps is realistic for liquid stocks.",
    "strategies": "The trading rules to test. Each is compared against simply buying and holding the stock.",
    "growth_of_1": "What $1 would have grown to following each strategy. The scale is logarithmic, so equal distances mean equal percentage gains.",
    "CAGR": "Compound annual growth rate: the average yearly return.",
    "Volatility": "How much returns bounce around, annualised. Higher means a bumpier ride.",
    "Sharpe": "Return per unit of risk (above the risk-free rate). Above 1 is good, above 2 is excellent; buy-and-hold on a stock is often 0.3-0.8.",
    "Sortino": "Like Sharpe, but only counts downside swings as risk.",
    "Max Drawdown": "The worst peak-to-bottom drop. This is the pain you'd have had to sit through.",
    "Calmar": "Annual return divided by the worst drawdown. Higher means better return for the pain.",
    "VaR 95% (1d)": "Value at Risk: on 95% of days the loss was smaller than this.",
    "CVaR 95% (1d)": "Expected shortfall: the average loss on the worst 5% of days.",
    "CF VaR 95% (1d)": "VaR adjusted for fat tails and skew (Cornish-Fisher), so it doesn't understate crash risk.",
    "Skew": "Whether big days tend to be up (positive) or down (negative).",
    "Excess Kurtosis": "How often extreme days happen compared with a normal bell curve. Higher means fatter tails.",
    "Hit Rate": "Share of days with a positive return.",
    "Beta": "How much the strategy moves with the stock itself. 1 = moves one-for-one, 0.5 = half as much.",
    "Alpha (ann.)": "Return the strategy earned beyond what its exposure to the stock explains.",
    "Tracking Error": "How far the strategy's returns wander from buy-and-hold.",
    "Information Ratio": "Extra return over buy-and-hold per unit of tracking error. Positive means the timing added value.",
    "Exposure": "Share of days the strategy was invested. Low exposure means cash most of the time.",
    "Trades": "Number of position changes (or completed trades for Confluence Pullback).",
    "drawdowns": "How far each strategy was below its previous peak over time.",
    "rolling_sharpe": "Sharpe ratio over each trailing year. It shows whether a strategy works consistently or only in certain periods.",
    "params": "Settings for each classic strategy. Changing them to fit one stock's past is the fastest way to fool yourself (overfitting).",
    # ---- Confluence Pullback -----------------------------------------------
    "min_score": "How many of the enabled 'point' confluences must line up before a trade is taken. Higher means fewer, pickier trades.",
    "stop_mode": "Where the stop-loss goes. Pullback low: just under the lowest low of the last 5 days. 20 EMA − ATR: one daily range under the 20-day EMA. 200-day MA: just under the 200-day (wide, as in your original MACD idea).",
    "t1_r": "First profit target, in multiples of your risk (R). R is the distance from entry to stop, so 1.5R on a $2 risk is $3 above entry.",
    "t2_r": "Final target for what's left after T1, in multiples of R. Set 0 to let the trailing exit decide.",
    "t1_fraction": "How much of the position to sell at T1. After T1 the stop moves to breakeven.",
    "trail": "After T1 is hit, exit the rest on a close below the 20-day EMA.",
    "exit_below_50": "Exit at the next open if price closes below the 50-day average: the pullback has turned into a breakdown.",
    "divergence": "If price makes a higher high but RSI makes a lower high within 14 days, momentum is fading: raise the stop to that day's low.",
    "rsi_fade": "If RSI goes above 70 and then drops back below, sell half of what's left.",
    "max_hold": "Close the trade after this many days if nothing else has, so capital doesn't sit in a stalled position.",
    "flow": "OBV adds all of a day's volume on up days and subtracts it on down days. VPT weights volume by the size of the move, so it's less jumpy.",
    "Win rate": "Share of completed trades that made money.",
    "Expectancy (R)": "Average result per trade in units of risk. +0.3R means that on average each trade made 30% of what you risked. Above 0 is a winning system.",
    "Profit factor": "Total gains divided by total losses. Above 1.5 is solid; below 1 loses money.",
    "Avg win": "Average return of winning trades.",
    "Avg loss": "Average return of losing trades.",
    "Avg bars held": "Average number of trading days each trade was open.",
    "R multiple": "The trade's profit or loss divided by the amount risked (entry minus stop). −1R is a full stop-out.",
    "ablation": "Re-runs the backtest with each must-pass rule switched off and at every minimum score, so you can see whether a filter actually helps or just cuts trades.",
    "rule_report": "Among trades that were taken, how they did when each point rule passed versus failed at entry. A rule that earns its place shows better results when it passed.",
    # ---- Trade setup / long-term ------------------------------------------
    "trade_status": "Whether today's daily bar gives a swing entry under your rules, is close to one, or doesn't qualify.",
    "entry": "Where the plan buys: the next open if the trigger fired today, otherwise just above today's high (a buy-stop order).",
    "stop": "The price where the trade is wrong and you get out. Set by the stop mode in the settings.",
    "risk_r": "R: the dollar distance from entry to stop. Targets are set in multiples of it.",
    "t1": "First target: sell part of the position here and move the stop to breakeven.",
    "t2": "Final target for the rest of the position.",
    "resistance": "The nearest price zone above where the stock turned down before. Rallies often stall there.",
    "support": "The nearest price zone below where the stock bounced before. Pullbacks often hold there.",
    "weekly_trend": "The long-term trend on the weekly chart: price vs its 40-week average (≈ 200-day) and the 10-week vs 40-week.",
    "core_long": "A checklist for multi-year holds: profitability, balance-sheet quality, cash generation, sensible valuation, trend and analyst revisions.",
}


def tip(key: str) -> str:
    return TERMS.get(key, "")
